#! /bin/bash
cd /usr/local/src
for a in *
do cd $a
	if [ -f configure ]
	then
		./configure
	fi
	make install
	cd /usr/local/src
done
cd
killall -9 dwm
$HOME/.xsession&
#See LICENSE file for copyright and license details
