.\" This program and its documentation are Public Domain.
.\" Steve Summit, scs@eskimo.com
.\" See http://www.eskimo.com/~scs/src/#line for possible updates.
.TH "LINE" 1
.SH "NAME"
.br
.ft R
line \- extract lines from a file
.SH "SYNOPSIS"
.br
.ft R
\fBline\fR
[
\fB\-nrv\fR
]
lines
[ files ]
.br
\fBline\fR
[
\fB\-nrv\fR
]
\fB\-f\fR
fromline
\fB\-t\fR
toline
[ files ]
.SH "DESCRIPTION"
.br
.ft R
.PP
\fIline\fR
extracts selected lines,
specified by line number,
from standard input or named files.
Line numbers are 1-based.
.br
.PP
The line numbers to be extracted may be specified in several ways.
The most basic is to indicate individual line numbers individually,
or line number ranges using the notation
\fIm\fR\-\fIn\fR.
Multiple line numbers or ranges may be separated by commas,
or entered as separate arguments.
For example,
the invocation
.sp
.nf
.ft C
	line 1,5,10\-20 inputfile
.ft R
.fi
.sp
would print lines 1, 5, and 10 through 20 of the file named
\fIinputfile\fR.
An equivalent invocation would be
.sp
.nf
.ft C
	line 1 5 10\-20 inputfile
.ft R
.fi
.sp
.br
.PP
In the
\fIm\fR\-\fIn\fR
notation,
either
\fIm\fR
or
\fIn\fR
(but not both) may be omitted.
The notation
\fB\-\fR\fIn\fR
means from the beginning of the file up to line
\fIn\fR.
The notation
\fIm\fR\fB\-\fR
means from line
\fIm\fR
to the end of the file.
.br
.PP
Because multiple line numbers may be entered as separate arguments,
there is an ambiguity
if an input filename has a name which looks like a number.
To resolve the ambiguity, use an alternative pathname for the file
which does not begin with a digit.
The simplest way to do so is to precede the numeric filename with "./".
.br
.SH "OPTIONS"
.br
.ft R
.IP "\fB\-n\fR"
Number output lines;
precede printed lines with their line numbers
(separated by a colon).
.br
.IP "\fB\-r\fR"
Random access.
By default, all line numbers selected and printed must be
monotonically increasing.
With
\fB\-r\fR,
it is permissible to "back up" in the input file
to print some earlier lines preceding those already printed.
To support this functionality,
\fIline\fR
builds an index of the lseek offsets of the lines it has seen.
Random-access selection with
\fB\-r\fR
is therefore possible only when the input is a true file,
since seeking is impossible on pipes.
Also, the line number index
may consume large amounts of memory for large files.
.br
.IP "\fB\-v\fR"
Invert;
print all lines
\fInot\fR
selected.
.br
.IP "\fB\-version\fR"
Print program's version number.
.br
.IP "\fB\-?\fR,\fB\-h\fR"
Print a brief help message.
.br
.SH "ALTERNATIVE LINE NUMBER SELECTION OPTIONS"
.br
.ft R
.PP
It is also possible to specify line numbers or ranges
using explicit option flags:
.IP "\fB\-f\fR \fIn\fR"
("from")
Start printing at line
\fIn\fR.
.br
.IP "\fB\-t\fR \fIn\fR"
("to")
Stop printing at line
\fIn\fR.
.br
.IP "\fB\-e\fR \fIn\fR"
("end")
Stop printing just before line
\fIn\fR,
that is, at line
\fIn\fR\-1.
.br
.IP "\fB\-p\fR \fIn\fR"
("plus")
Print
\fIn\fR
lines past the last-specified start line.
That is,
.sp
.nf
.ft C
	\-f m \-p n
.ft R
.fi
.sp
is equivalent to
.sp
.nf
.ft C
	\-f m \-t m+n\-1
.ft R
.fi
.sp
(or to \fC\-f m \-e m+n\fR ).
.br
.br
.PP
Any number of
\fB\-f\fR,
\fB\-t\fR,
\fB\-e\fR,
and
\fB\-p\fR
options may appear.
When these options are used,
lone numbers
on the command line
are
\fInot\fR
interpreted as line numbers or ranges,
and are therefore unambiguously usable as filenames.
.br
.PP
The
\fB\-f\fR,
\fB\-t\fR,
\fB\-e\fR,
and
\fB\-p\fR
options are intended for use in shell scripts,
when a complicated set of line number ranges is being built up on-the-fly,
and when constructing a single string
containing many dashes and commas
would be even more cumbersome.
.br
.SH "MORE DESCRIPTION"
.br
.ft R
.PP
When
\fIline\fR
is invoked with multiple input filenames,
the specified lines are selected from all files.
For example,
.sp
.nf
.ft C
	line 5,10 a b c
.ft R
.fi
.sp
would print lines 5 and 10 of file
\fIa\fR,
followed by lines 5 and 10 of file
\fIb\fR,
followed by lines 5 and 10 of file
\fIc\fR.
To select lines from the concatenation of many input files,
use
<a href="/~scs/cgi-bin/manredir.cgi?name=cat&sec=1">\fIcat(1)\fR</a>
and a pipeline:
.sp
.nf
.ft C
	cat a b c | line 5,10
.ft R
.fi
.sp
.br
.PP
The
\fIm\fR\-\fIn\fR
line-selection syntax also supports "relative" (counted) range increments,
analogous to the
\fB\-p\fR
option.
The notation
\fIm\fR\fB:\fR\fIn\fR
is equivalent to
\fIm\fR\fB\-\fR\fIm\fR+\fIn\fR\-1.
For example,
the invocation
.sp
.nf
.ft C
	line 5:10,20 inputfile
.ft R
.fi
.sp
would print 10 lines beginning with line 5
(that is, lines 5 through 14),
followed by line 20.
.br
.SH "HISTORY"
.br
.ft R
.PP
\fIline\fR
was inspired by
a program of the same name and basic functionality
conceived by Philip Lantz at Tektronix MDP circa 1985.
.br
.PP
This documentation corresponds to version 2.3 of the program.
.br
.PP
See
\fChttp://www.eskimo.com/~scs/src/#line\fR
for possible updates.
.br
.SH "SEE ALSO"
.br
.ft R
<a href="/~scs/cgi-bin/manredir.cgi?name=head&sec=1">\fIhead(1)\fR</a>,
<a href="/~scs/cgi-bin/manredir.cgi?name=tail&sec=1">\fItail(1)\fR</a>,
<a href="/~scs/cgi-bin/manredir.cgi?name=sed&sec=1">\fIsed(1)\fR</a>,
<a href="column.man.html">\fIcolumn\fR</a>
.SH "AUTHOR"
.br
.ft R
.PP
Steve Summit,
\fCscs@eskimo.com\fR
.br
